### ISSUE TITLE
No Device Information when connecting multiple DS2438

### ISSUE THREAD

**Issue by JuergenST** [habeIchVergessen/ESP-1wire-WLAN-Gateway#18]
Hello, 

I've connected 2 DS2438 Sensors to my DS2482 Module and connected it to my FHEM installation.
For the integrated temperature sensors, I get 1 Entry for each of the 2 DS2438, but for the values
voltage
current 
capacity
I only get 1 value, as they are not prefixed with the Sensor ID.

I've identified the statements in your sourcecode, where I think that there is an extension needed:
it's in

`void readBatteries(Esp1wire::DeviceType filter)`

Lines 366 - 368, and 379-381:

```
 if (device->requestVAD(&voltage, &current, &capacity)) {
      message += SensorDataValuePort(Voltage, "VAD", String(voltage, 3));
      message += SensorDataValuePort(Current, "VAD", String(current, 3));
      message += SensorDataValuePort(Capacity, "VAD", String(capacity, 3));
#ifdef _MQTT_SUPPORT
      if (sendMqtt) {
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Voltage, "VAD"), String(voltage, 3)); 
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Current, "VAD"), String(current, 3)); 
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Capacity, "VAD"), String(current, 3)); 
      }
#endif
    }
    // requestVdd depends on device config (default vad only)
    if (device->getRequestVdd() && device->requestVDD(&voltage, &current, &capacity)) {
      message += SensorDataValuePort(Voltage, "VDD", String(voltage, 3));
      message += SensorDataValuePort(Current, "VDD", String(current, 3));
      message += SensorDataValuePort(Capacity, "VDD", String(capacity, 3));
#ifdef _MQTT_SUPPORT
      if (sendMqtt) {
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Voltage, "VDD"), String(voltage, 3)); 
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Current, "VDD"), String(current, 3)); 
        espMqtt.publish(device->getOneWireDeviceID(), SensorNamePort(Capacity, "VDD"), String(current, 3)); 
      }
#endif
```

There, the device->getOneWireDeviceID() seems missing.

As I can't get it compiled (missing some declarations (DEVICE, LATCH,Sense ..), I'd kindly ask you to add them to the code.

![Bildschirmfoto 2020-10-29 um 22 12 07](https://user-images.githubusercontent.com/668895/97633872-0edebf80-1a35-11eb-9f6b-c1cab0a31848.png)

**Comment by habeIchVergessen** [comment]
solved in [955572a](https://github.com/habeIchVergessen/ESP-1wire-WLAN-Gateway/commit/955572a87750af12581d1d7f782a1df7f8eecc69)
