### ISSUE TITLE
New BIN file

### ISSUE THREAD

**Issue by FrankStm** [habeIchVergessen/ESP-1wire-WLAN-Gateway#19]
Hi,

i use your program for many 1wire temperature (DS18B20) und humidity components
(DS2438/HIH5031) on my central air handling unit. Thank you very much for coding!

I saw that you updated the file "SP-1wire-WLAN-Gateway.ino". 
It is possible that you are build a neu BIN file?
I have problems integrating the korrekt libraries.
Sorry, i´m not a professional programmer. 

Greetings and Thanks,
Frank

**Comment by habeIchVergessen** [comment]
[1f1fc8e](https://github.com/habeIchVergessen/ESP-1wire-WLAN-Gateway/commit/1f1fc8e08aeb09ce13d10171a3b9b6e234ebbce9)
